[project]
name = "kube"
revision = "1.0"

[profiles.default]
PGHOST = { description = "Database host", required = true }
PGUSER = { description = "Database user", required = true }
PGPASSWORD = { description = "Database password", required = true }
