apiVersion: v1
kind: Service
metadata:
  name: traefik-tailscale
  namespace: kube-system
  annotations:
    tailscale.com/expose: "true"
    tailscale.com/hostname: "k8s-ingress"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  externalTrafficPolicy: Local
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      port: 80
      targetPort: web
    - name: websecure
      port: 443
      targetPort: websecure
    - name: postgres
      port: 5432
      targetPort: postgres
