apiVersion: v2
name: tailscale
description: Tailscale operator
type: application
version: 0.1.0
appVersion: 1.90.6
dependencies:
  - name: tailscale-operator
    version: 1.90.6
    repository: https://pkgs.tailscale.com/helmcharts
