{{- if .Values.enableTailscaleOnlyMiddleware }}
apiVersion: traefik.io/v1alpha1
kind: MiddlewareTCP
metadata:
  name: tailscale-tcp-ingress-only
spec:
  ipAllowList:
    sourceRange:
      - 10.42.0.0/16
---
{{- end }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: postgres-ingressroute
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`pg.tokhirov.uz`)
      services:
        - name: postgres-postgresql
          port: 5432

      {{- if .Values.enableTailscaleOnlyMiddleware }}
      middlewares:
        - name: tailscale-tcp-ingress-only
      {{- end }}

  tls:
    passthrough: true
