apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: httpbin-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`httpbin.tokhirov.uz`)
      services:
        - name: httpbin
          port: http
  tls:
    certResolver: letsencrypt
