apiVersion: v2
name: metabase
type: application
version: 1.0.0
dependencies:
  - name: metabase
    version: 2.22.2
    repository: https://pmint93.github.io/helm-charts
  - name: postgresql
    version: 18.1.9
    repository: https://charts.bitnami.com/bitnami
