apiVersion: v2
name: httpbin
description: httpbin for debugging
type: application
version: 0.1.0
appVersion: 0.1.1
dependencies:
  - name: httpbin
    version: 0.1.1
    repository: https://matheusfm.dev/charts
