enableTailscaleOnlyMiddleware: true

superset:
  image:
    repository: superset
    tag: 5.0.0
    pullPolicy: Never

  configOverrides:
    features: |
      FEATURE_FLAGS = {
          'PLAYWRIGHT_REPORTS_AND_THUMBNAILS': True,
      }

  supersetNode:
    connections:
      db_host: postgres-postgresql.postgres.svc.cluster.local

  postgresql:
    enabled: false

  redis:
    image:
      tag: latest
