apiVersion: v2
name: authentik
description: Authentik OIDC/SAML provider with WebFinger support
type: application
version: 0.1.0
appVersion: 2025.10.0
dependencies:
  - name: authentik
    version: 2025.10.0
    repository: https://charts.goauthentik.io
  - name: authentik-webfinger-proxy
    version: "0.1.2"
    repository: oci://ghcr.io/sudo-kraken/helm-charts
