authentik:
  authentik:
    log_level: info
    error_reporting:
      enabled: false

    email:
      host: "mail.mukhtarov.net"
      port: 465
      username: "authentik@tokhirov.uz"
      from: "authentik@tokhirov.uz"
      use_ssl: true

  postgresql:
    enabled: true

  redis:
    enabled: true

  server:
    ingress:
      enabled: false

# WebFinger configuration
webfinger:
  enabled: true
  domain: tokhirov.uz
  ingressRoute:
    enabled: true
    certResolver: letsencrypt

# Pass values to the authentik-webfinger-proxy subchart
authentik-webfinger-proxy:
  env:
    - name: DOMAIN
      value: auth.tokhirov.uz
    - name: APPLICATION
      value: tailscale
