apiVersion: v2
name: postgresql
description: PostgreSQL database
type: application
version: 0.1.0
appVersion: 18.1.9
dependencies:
  - name: postgresql
    version: 18.1.9
    repository: https://charts.bitnami.com/bitnami
